import os
import pandas as pd
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables (API URL & KEY)
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# Pastikan Supabase terkonfigurasi
def get_supabase_client() -> Client:
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise ValueError("SUPABASE_URL dan SUPABASE_KEY belum diatur. Tambahkan ke .env atau Streamlit Secrets.")
    return create_client(SUPABASE_URL, SUPABASE_KEY)


# Inisialisasi tabel mutasi barang
def create_table_if_not_exists(supabase: Client):
    try:
        response = supabase.table("mutasi_barang").select("*").limit(1).execute()
        print("Tabel 'mutasi_barang' sudah ada.")
    except Exception:
        print("Pastikan Anda telah membuat tabel 'mutasi_barang' di Supabase.")
        print("Gunakan query SQL berikut di dashboard Supabase Anda:\n")
        print("""
        CREATE TABLE public.mutasi_barang (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            uraian_barang text,
            item_keluar integer,
            satuan text,
            tanggal_keluar date,
            keterangan text
        );
        """)


# Simpan dataframe ke Supabase
def upload_to_supabase(df: pd.DataFrame):
    supabase = get_supabase_client()
    create_table_if_not_exists(supabase)
    data_records = df.to_dict(orient="records")
    response = supabase.table("mutasi_barang").insert(data_records).execute()
    return response


# Ambil data dari Supabase
def fetch_data_from_supabase():
    supabase = get_supabase_client()
    data = supabase.table("mutasi_barang").select("*").execute()
    return pd.DataFrame(data.data)


# Hapus semua data di tabel (opsional)
def clear_supabase_table():
    supabase = get_supabase_client()
    supabase.table("mutasi_barang").delete().neq("id", 0).execute()
    print("Semua data berhasil dihapus.")


if __name__ == "__main__":
    # Contoh penggunaan
    df_example = pd.DataFrame({
        "uraian_barang": ["Kabel Listrik", "Lampu LED", "Stop Kontak"],
        "item_keluar": [10, 20, 15],
        "satuan": ["meter", "buah", "buah"],
        "tanggal_keluar": ["2025-10-05", "2025-10-04", "2025-10-03"],
        "keterangan": ["Proyek A", "Gudang Utama", "Cadangan"]
    })

    print("Mengunggah data contoh ke Supabase...")
    upload_to_supabase(df_example)

    print("Data di Supabase:")
    print(fetch_data_from_supabase())
